# This is a basic workflow to help you get started with Actions

name: Build OLM Chart

on: [push]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs commands using the runners shell
      - name: Check for updates in chart
        run: .bin/update-chart.sh
      - name: Commit files # transfer the new html files back into the repository
        if: github.ref != 'refs/heads/develop' && github.ref != 'refs/heads/main'
        run: |
          git config --local user.name  ${{ github.actor }}        
          git config --local user.email "${{ github.actor }}@users.noreply.github.com"
          git add .
          git commit -m "Updating OLM chart"
      - name: Push changes # push the output folder to your repo
        uses: ad-m/github-push-action@master
        if: github.ref != 'refs/heads/develop' && github.ref != 'refs/heads/main'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          force: true
