# This is a basic workflow to help you get started with Actions

name: Build OLM Chart

on:
  merge_group:
  push:
    branches: [ develop, main ]
  pull_request:
    branches: [ develop ]
  schedule:
    - cron: '0 0 * * WED'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    permissions:
      # required to push a commit
      contents: write
      # required to create a pull request
      pull-requests: write

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      # Runs commands using the runners shell
      - name: Check for updates in chart
        run: .bin/update-chart.sh

      # push the change if exists
      - uses: int128/update-generated-files-action@v2
        with:
          commit-message: "chore: Update OLM chart"
